export const chats = [
  {
    id: 1,
    name: "Tony Reichert",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/1.png",
    lastMessage: "Hey, are you available for a meeting?",
    lastMessageTime: "2024-04-21T12:45:00.000Z",
  },
  {
    id: 2,
    name: "Zoey Lang",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/1.png",
    lastMessage: "Can you review my last commit?",
    lastMessageTime: "2024-04-21T15:00:00.000Z",
  },
  {
    id: 3,
    name: "Jane Fisher",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/2.png",
    lastMessage: "Thanks for your help today!",
    lastMessageTime: "2024-04-21T13:30:00.000Z",
  },
  {
    id: 4,
    name: "William Howard",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/2.png",
    lastMessage: "I'm on vacation until next week.",
    lastMessageTime: "2024-04-20T09:20:00.000Z",
  },
  {
    id: 5,
    name: "Kristen Copper",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/3.png",
    lastMessage: "The sales targets for this quarter are impressive.",
    lastMessageTime: "2024-04-21T16:45:00.000Z",
  },
  {
    id: 6,
    name: "Brian Kim",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/3.png",
    lastMessage: "Let's discuss the project timeline.",
    lastMessageTime: "2024-04-22T08:15:00.000Z",
  },
  {
    id: 7,
    name: "Michael Hunt",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/4.png",
    lastMessage: "I need your feedback on the design.",
    lastMessageTime: "2024-04-22T11:00:00.000Z",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/4.png",
    lastMessage: "Can we schedule an HR meeting tomorrow?",
    lastMessageTime: "2024-04-21T10:30:00.000Z",
  },
  {
    id: 9,
    name: "Frank Harrison",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/5.png",
    lastMessage: "Please approve the financial report.",
    lastMessageTime: "2024-04-21T14:15:00.000Z",
  },
  {
    id: 10,
    name: "Emma Adams",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/5.png",
    lastMessage: "Operations team meeting has been rescheduled.",
    lastMessageTime: "2024-04-21T16:00:00.000Z",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/7.png",
    lastMessage: "Looking forward to our next development sprint.",
    lastMessageTime: "2024-04-21T09:45:00.000Z",
  },
  {
    id: 12,
    name: "Megan Richards",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/7.png",
    lastMessage: "The product launch plan needs to be updated.",
    lastMessageTime: "2024-04-22T11:30:00.000Z",
  },
  {
    id: 13,
    name: "Oliver Scott",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/8.png",
    lastMessage: "Security protocols will be revised next week.",
    lastMessageTime: "2024-04-22T10:00:00.000Z",
  },
  {
    id: 14,
    name: "Grace Allen",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/8.png",
    lastMessage: "We need more content for the upcoming marketing campaign.",
    lastMessageTime: "2024-04-21T17:30:00.000Z",
  },
  {
    id: 15,
    name: "Noah Carter",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/9.png",
    lastMessage: "The network upgrade is scheduled for this weekend.",
    lastMessageTime: "2024-04-20T12:20:00.000Z",
  },
  {
    id: 16,
    name: "Ava Perez",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/9.png",
    lastMessage: "Sales team is meeting first thing Monday morning.",
    lastMessageTime: "2024-04-21T08:30:00.000Z",
  },
  {
    id: 17,
    name: "Liam Johnson",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/11.png",
    lastMessage: "Can you check the latest data analysis report?",
    lastMessageTime: "2024-04-21T15:10:00.000Z",
  },
  {
    id: 18,
    name: "Sophia Taylor",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/11.png",
    lastMessage: "QA found a few bugs that need immediate attention.",
    lastMessageTime: "2024-04-22T14:05:00.000Z",
  },
  {
    id: 19,
    name: "Lucas Harris",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/male/12.png",
    lastMessage: "Updating server permissions, expect some downtime.",
    lastMessageTime: "2024-04-22T09:50:00.000Z",
  },
  {
    id: 20,
    name: "Mia Robinson",
    avatar: "https://d2u8k2ocievbld.cloudfront.net/memojis/female/12.png",
    lastMessage: "Please review the operation coordination for next quarter.",
    lastMessageTime: "2024-04-21T16:40:00.000Z",
  },
];
